# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build pedro-yan`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t pedro-yan`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system pedro-yan && \
          adduser --system -G pedro-yan pedro-yan

COPY dist/pedro-yan pedro-yan/
RUN chown -R pedro-yan:pedro-yan .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix pedro-yan --omit=dev -f install

CMD [ "node", "pedro-yan" ]
